[package]
name = "rdap-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rdap = { path = "../rdap" }
tokio = { version = "1.14", features = [ "full" ] }